export enum Process {
    // manufacturing & packaging
    UNDERWENT_MIXING_ENCAPSULATION = 'UNDERWENT_MIXING_ENCAPSULATION',
    LABELLING_PACKAGING = 'LABELLING_PACKAGING',
    // importer / warehousing
    READY_TO_SHIP = 'READY_TO_SHIP',
    SHIPPED = 'SHIPPED',
    STORE_IN_WAREHOUSE = 'STORE_IN_WAREHOUSE',
    DELIVERED = 'DELIVERED',
    REJECTED = 'REJECTED',
    RETURNED = 'RETURNED',
}


